// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id: 'us-west-2:b05e6ebf-8c20-4bec-bb1b-669d005dc1e4',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_T2FcSEm2H',
  aws_user_pools_web_client_id: '1i9b7mj5thstaskt6qbv54ivhq',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://fes5hbrbvzdm3em3rfmtmqbiwa.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: 'da2-5fiikjxfujg2djhgiiwmd3u76m',
};

export default awsmobile;
